### ISSUE TITLE
Разработать интерфейс "Главного меню" и функционал окна "Начать тест"

### ISSUE THREAD

**Issue by caeser321** [trpo2021/cw-ip-017_iv-023_quizrunner#4]
Консоль

**Comment by Rebirth3125** [comment]
> * Главное меню
> 
> > В окне главное меню будет находится кнопка "Начать тест"
> 
> * Тест
> 
> > При нажатии "Начать тест" перед пользователем будет выведен тест с 25 вопросами по 4 варианта ответа в каждом вопросе. В котором пользователю будет предоставлен кадр из фильма, а он в свою очередь должны угадать откуда данный кадр из предложенных вариантов ответа.

**Comment by Rebirth3125** [comment]
> * Главное меню
> 
> > В окне главное меню будет находится кнопка "Начать тест"
> 
> * Тест
> 
> > При нажатии "Начать тест" перед пользователем будет выведен тест с 25 вопросами по 4 варианта ответа в каждом вопросе. В котором пользователю будет предоставлен кадр из фильма, а он в свою очередь должны угадать откуда данный кадр из предложенных вариантов ответа.
